import type { Metadata } from "next"
import "./globals.css"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: '#000000',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/icons/icon512_rounded.png" />
        <meta name="theme-color" content="#000000" />
      </head>
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
